[workspace]
resolver = "2"
members = [
    "alumet",
    "alumet-api-dynamic",
    "alumet-api-macros",
    "app-agent",
    "app-relay-collector",
    "plugin-csv",
    "plugin-k8s",
    "plugin-influxdb",
    "plugin-nvidia",
    "plugin-oar2",
    "plugin-oar3",
    "plugin-perf",
    "plugin-rapl",
    "plugin-relay",
    "plugin-socket-control",
    "test-dynamic-plugin-rust",
    "test-dynamic-plugins",
]
