version: 2.1

jobs:
  build_and_test:
    resource_class: large
    docker:
      - image: cimg/rust:1.78.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Create concatenated cache key
          command: |
            find -name 'Cargo\.toml' | xargs cat > .combined_cache_key
            if [ -f .cargo/config.toml ]; then
              cat .cargo/config.toml >> .combined_cache_key
            fi
            if [ -f Cargo.lock ]; then
              cat Cargo.lock >> .combined_cache_key
            fi
      - run:
          name: Install required packages.
          command: sudo apt-get update && sudo apt-get install llvm-dev libclang-dev protobuf-compiler --no-install-recommends
      - restore_cache:
          keys:
            - v1-cache-{{ checksum ".combined_cache_key" }}
      - run:
          name: Run Tests (including doc tests)
          command: "CONTINUE_TEST_IF_NO_POWERCAP=true cargo test"
      - run:
          name: Installing cargo-cache
          command: "cargo install cargo-cache --no-default-features --features ci-autoclean cargo-cache"
      - run:
          name: Optimizing the cache
          command: "cargo cache"
      - save_cache:
          key: v1-cache-{{ checksum ".combined_cache_key" }}
          paths:
            - ~/.cargo
            #- {{ .Environment.CARGO_HOME }}
  lint:
    resource_class: medium
    docker:
      - image: cimg/rust:1.78.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Create concatenated cache key
          command: |
            find -name 'Cargo\.toml' | xargs cat > .combined_cache_key
            if [ -f .cargo/config.toml ]; then
              cat .cargo/config.toml >> .combined_cache_key
            fi
            if [ -f Cargo.lock ]; then
              cat Cargo.lock >> .combined_cache_key
            fi
      - run:
          name: Install required packages.
          command: sudo apt-get update && sudo apt-get install llvm-dev libclang-dev protobuf-compiler --no-install-recommends
      - restore_cache:
          keys:
            - v1-cache-{{ checksum ".combined_cache_key" }}
      - run:
          name: Check formatting
          command: "cargo fmt --check"
      - run:
          name: Run Clippy
          command: "cargo clippy --no-deps"
      - run:
          name: Installing cargo-cache
          command: "cargo install cargo-cache --no-default-features --features ci-autoclean cargo-cache"
      - run:
          name: Optimizing the cache
          command: "cargo cache"
      - save_cache:
          key: v1-cache-{{ checksum ".combined_cache_key" }}
          paths:
            - ~/.cargo
            #- {{ .Environment.CARGO_HOME }}
  miri_test:
    resource_class: medium
    docker:
      - image: cimg/rust:1.78.0
    steps:
      - checkout
      - run: cargo --version && rustup --version
      - run:
          name: Install Miri on nightly rust
          command: "rustup +nightly component add miri"
      - run:
          name: Run Miri on some tests
          command: "cd alumet && cargo +nightly miri test -- ffi"
          environment:
            SKIP_BINDGEN: true

workflows:
  test_and_lint:
    jobs:
      - build_and_test
      - lint
      - miri_test
