[package]
name = "app-agent"
version = "0.5.0"
edition = "2021"
description = "Metric collector agent to install on each node."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alumet = { path = "../alumet" }
anyhow = "1.0.79"
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.2"
humantime-serde = "1.1.1"
log = "0.4.20"
plugin-influxdb = { version = "0.1.0", path = "../plugin-influxdb" }
plugin-perf = { version = "0.1.0", path = "../plugin-perf" }
plugin-rapl = { version = "0.3.0", path = "../plugin-rapl" }
plugin-socket-control = { version = "0.1.0", path = "../plugin-socket-control" }
serde = { version = "1.0.198", features = ["derive"] }
toml = "0.8.12"

[[bin]]
name = "alumet-agent"
path = "src/main.rs"
