[package]
name = "plugin-rapl"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]


[dependencies]
alumet = { path = "../alumet" }
anyhow = "1.0.79"
humantime-serde = "1.1.1"
indoc = "2.0.5"
log = "0.4.20"
perf-event-open-sys = "4.0.0"
regex = "1.10.3"
serde = { version = "1.0.198", features = ["derive"] }

[lints]
workspace = true
